// skills
export const GET_SKILLS = 'GET_SKILLS';
export const SET_USER = 'SET_USER';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';

// messages
export const START_FETCHING_MESSAGES = 'START_FETCHING_MESSAGES';
export const GET_MESSAGE = 'GET_MESSAGE';
export const MESSAGE_LIST = 'MESSAGE_LIST';

export const SET_CURRENT_THREAD = 'SET_CURRENT_THREAD';
export const GET_MESSAGES_BY_THREAD = 'GET_MESSAGES_BY_THREAD';
export const MESSAGES_BY_THREAD_LIST = 'MESSAGES_BY_THREAD_LIST';
export const START_SENDING_MESSAGE = 'START_SENDING_MESSAGE';
export const MESSAGE_ADDED_TO_THREAD = 'MESSAGE_ADDED_TO_THREAD';
export const UPDATE_THREAD_VIEW_HEIGHT = 'UPDATE_THREAD_VIEW_HEIGHT';

// Notifications
export const GET_FROM_NOTIFICATION = 'GET_FROM_NOTIFICATION';
export const GET_TO_NOTIFICATION = 'GET_TO_NOTIFICATION';
