# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'accomplish' do
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Database', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'GoogleAppMeasurement', '~> 5.2.0'
  pod 'Firebase/Storage', '~> 5.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for accomplish

end
